config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "timeslots#index"
  resources :timeslots
  resources :bookings, only: [:create]
  resources :exchanges, only: [:create, :index, :update, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :timeslot
end

app/models/exchange.rb
class Exchange < ApplicationRecord
belongs_to :user_1, class_name: 'User', dependent: :destroy
belongs_to :user_2, class_name: 'User', dependent: :destroy
belongs_to :booking_2, class_name: 'Booking', dependent: :destroy
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :task, presence: true
  validates :number_employee, presence: true
  default_scope -> { order(:start_time) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :timeslots
  validates :department, presence: true, numericality: { only_integer: true, in: 1..14 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :department, :manager])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :department, :manager])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @user = current_user
    @timeslot = Timeslot.find(params[:timeslot_id])
    @booking = Booking.new(timeslot_id: @timeslot.id, user_id: @user.id)
  end

  def create
    @bookings = Booking.all
    @timeslot = Timeslot.find(params[:timeslot_id])
    @booking = Booking.new(:user_id => current_user.id, :timeslot_id => params[:timeslot_id])
    if @bookings.where(timeslot_id: params[:timeslot_id]).count < @timeslot.number_employee
      @booking.save
      flash[:notice] = "Votre créneau a bien été réservé"
      redirect_to timeslots_path
    else
      flash[:alert] = "Désolé, il a deja assez de participants pour ce créneau"
      redirect_to timeslots_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:timeslot_id, :user_id)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def index
    @exchanges = Exchange.all
    @exchanges_demands = Exchange.where(user_2_id: current_user.id)
    @exchanges_resquests = Exchange.where(user_1_id: current_user.id)

  end

  def create
    @exchange = Exchange.new(exchange_params)
    if @exchange.save
      flash[:notice] = "Demande d'échange envoyée"
    else
      flash[:alert] = @exchange.errors.full_messages.join(", ")
    end
    redirect_to timeslots_path
  end

  def update
    @exchange = Exchange.find(params[:id])
    @status = params[:status]
    booking = Booking.find(@exchange.booking_2_id)
    if @exchange.update(status: params[:status])
      if @status == "Accepté"
        flash[:notice] = "Échange accepté"
      booking.update(user_id: @exchange.user_1_id)
      elsif @status == "Refusé"
        flash[:notice] = "Échange refusé"
      end
    else
      flash[:alert] = @exchange.errors.full_messages.join(", ")
      redirect_to exchanges_path
    end
  end

  def destroy
    @exchange = Exchange.find(params[:id])
    @exchange.destroy
    redirect_to exchanges_path
  end

  private

  def exchange_params
    params.permit(:user_1_id, :booking_2_id, :user_2_id, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  def index
    @timeslots = Timeslot.where(
      start_time: Time.now.beginning_of_week..Time.now.end_of_week,
      end_time: Time.now.beginning_of_week..Time.now.end_of_week
    )
    @bookings = Booking.all
  end

  def new
    @timeslot = Timeslot.new
  end

  def create
    @timeslot = Timeslot.new(timeslot_params)
    if @timeslot.save
      redirect_to timeslots_path
    else
      render :new
    end
  end

  def edit
    @timeslot = Timeslot.find(params[:id])
  end

  def duplicate(week)
    events = Timeslot.where()
  end
  def update
    @timeslot = Timeslot.find(params[:id])
    if @timeslot.update(timeslot_params)
      redirect_to timeslots_path
    else
      render :edit
    end

  end
  private

  def timeslot_params
    params.require(:timeslot).permit(:start_time, :end_time, :task, :number_employee)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchanges/index.html.erb
<div class="container mt-5">
<h1>Mes échanges d'horaire</h1>
<h3>Mes demandes en attente</h3>

<%# Demandes reçues en attente %>

            <%# Si il en a avec le status attente & user_2: current_user %>
<div class="card">
    <% if @exchanges_demands.where(user_1_id: current_user).present? %>
      <% @exchanges_demands.each do |exchange|%>
          <% if exchange.status == "En attente" %>
              <div class="card-body">
                  <p><%= User.find(exchange.user_1_id).name %> souhaite échanger son horaire avec vous</p>
                  <%# Doit être changé en link_to pour raffraichir la page pour plus que ça s'affiche %>
                 <%= button_to "Accepter", exchange_path(exchange, status: "Accepté"), method: :patch, data: { turbo: "false" }, class: "btn btn-success" %>
                  <%= button_to "Refuser", exchange_path(exchange, status: "Refusé"), method: :patch, data: { turbo: "false" }, class: "btn btn-danger" %>
              </div>
          <% end %>
      <% end %>
      <% else %>
        <p>Vous n'avez pas de demande d'échange en attente</p>
    <% end %>
</div>

<h3> Demandes reçues</h3>
<%# Demandes crées en attente  %>
<% if @exchanges_requests.present?  %>
  <% @exchanges_requests.each do |exchange| %>
    <% if exchange.status == "En attente" %>
      <div class="card-body">
        <p>Vous avez demandé à échanger votre horaire avec <%= User.find(exchange.user_2_id).name %></p>
        <%= link_to "Annuler", exchange_path(exchange), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      </div>
    <%end %>
  <%end %>
<% else %>
  <p>Vous n'avez pas de demande d'échange en attente</p>
<% end %>

<%# Demandes passées %>

<% if @exchanges.present? %>
  <% @exchanges.order(:created_at).each do |exchange| %>
     <% if exchange.status == "Accepté" || exchange.status == "Refusé" %>
      <div class="card-body">
        <% if exchange.user_1 == current_user %>
          <p>Votre demande d'échange avec <%= User.find(exchange.user_2_id).name %> a été <%= exchange.status%>e</p>
        <% elsif exchange.user_2 == current_user %>
          <p>Vous avez <%= exchange.status %> la demande d'échange de <%= User.find(exchange.user_1_id).name%></p>
        <% end %>
      </div>
     <%end %>

  <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planning</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <% I18n.locale = :fr %>

  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://c8.alamy.com/comp/2A94P01/simple-clear-cool-design-concept-for-your-business-logo-2A94P01.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">Bonjour <%= current_user.name %>
            </li>
          <li class="nav-item active">
            <%= link_to "Home", timeslots_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Echanges", exchanges_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
    <% month = ["  ", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre", "Octobre", "Novembre", "Décembre"] %>
      <%= month[calendar.start_date.month]%>
      <%= t('simple_calendar.week', default: 'Semaine') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Précédent'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: "Aujourd'hui"), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Suivant'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/timeslots/_form.html.erb
<%= form_for(@timeslot) do |f| %>

  <div class=" form_field">
    <%= f.label :task %>
    <%= f.text_field :task %>
  </div>

  <div class=" form_field">
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %>
  </div>

  <div class="form_field">
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %>
  </div>

  <div class="form_field">
    <%= f.label :number_employee %>
    <%= f.number_field :number_employee, min: 1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<%= render "form" %>

app/views/timeslots/index.html.erb
<!-- Main container for the calendar -->
<div class="container mt-5 text-center">

    <!-- Display a link to create a new timeslot if the current user is a manager -->
    <%= link_to "nouveau", new_timeslot_path if current_user.manager? %>

    <!-- Display a week calendar with timeslots as events -->
    <%= week_calendar(events: @timeslots) do |date|%>
        <div class="day">
            <%= date.day %>

            <% @timeslots.each do |timeslot| %>
                <% bookings = @bookings.where(timeslot_id: timeslot.id) %>

                <% if timeslot.start_time >= date.beginning_of_day && timeslot.start_time < date.end_of_day %>
                    <div class="mt-5 card timeslot">
                        <p id="timeslot-title"><%= timeslot.task %></p>
                        <div class="timeslot-time">
                            <p id="timeslot-start-time"><%= timeslot.start_time.strftime("%H:%M -->") %></p>
                            <p id="timeslot-end-time"><%= timeslot.end_time.strftime(" %H:%M") %></p>
                        </div>
                        <p id="timeslot-number-employee"> <%= timeslot.number_employee %> <%= timeslot.number_employee > 1 ? " Collaborateurs" : " Collaborateur" %></p>

                            <p> current user id : <%= current_user.id %></p>
                        <ul><li>Inscrits :</li>
                            <%# INSCRIPTIONS  %>
                            <% bookings.each do |booking| %>
                              <div class= "d-flex">
                                  <li><%= booking.user.name %></li>
                                  <%# Boutons --> Conditions  %>
                                  <% if bookings.size >= timeslot.number_employee && bookings.map(&:user_id).exclude?(current_user.id) %>
                                      <% if Exchange.where(booking_2_id: booking, user_2_id: booking.user, user_1_id: current_user, status: "En attente").size >= 1%>
                                          <li class="btn btn-primary">Demande en attente</li>
                                      <% elsif Exchange.where(booking_2_id: booking, user_2_id: booking.user, user_1_id: current_user, status: "En attente").size <= 1 %>
                                          <li><%= button_to "Request exchange", exchanges_path(user_1_id: current_user.id, user_2_id: booking.user_id, booking_2_id: booking.id, status: "En attente"), method: :post, remote: true, class: 'btn btn-warning' %></li>
                                      <% end %>
                              </div>
                                  <% end %>
                            <% end %>
                        </ul>

                        <!-- Display edit link if the current user is a manager -->
                        <%= link_to "modifier", edit_timeslot_path(timeslot) if current_user.manager? %>
                        <%# Display Take the slot if employee and room for it %>
                        <% if current_user.manager? == false && bookings.size < timeslot.number_employee && bookings.map(&:user_id).exclude?(current_user.id) %>
                            <%= button_to 'Book this slot', bookings_path(timeslot_id: timeslot.id), method: :post, remote: true, class: 'btn btn-primary' %>
                        <% end %>
                    </div>
                <% end  %>
            <% end  %>
        </div>
    <%end  %>
</div>

app/views/timeslots/new.html.erb
<div class="container">

  <%= render "form" %>
</div>